server {
    listen 80;
    listen [::]:80;

    root /usr/share/nginx/html;

    location /games/ {
        try_files $uri $uri/ /games/dynamic.html;
    }

    location /sessions/ {
        try_files $uri $uri/ /sessions/dynamic.html;
    }

    location /watchparty/ {
        try_files $uri $uri/ /watchparty/dynamic.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
